name: Remove

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 3 * *'

jobs:
  Delete-Workflow:
    runs-on: ubuntu-20.04
    steps:
    - name: 删除工作流
      uses: FunctionXJB/delete-workflow-runs@main
      continue-on-error: true
      with:
        retain_days: 2
        keep_minimum_runs: 1